/* Local assets only: the basemap is the sole browser network dependency. */
const $ = id => document.getElementById(id);
let rf, candidates, result, placing = null, busy = false, selected = 0;
const map = L.map('map').setView([60, 10.8], 9);
const osm = L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {maxZoom:19, attribution:'© OpenStreetMap contributors'}).addTo(map);
const topo = L.tileLayer('https://cache.kartverket.no/v1/wmts/1.0.0/topo/default/webmercator/{z}/{y}/{x}.png', {maxZoom:18, attribution:'© Kartverket'});
L.control.layers({'OpenStreetMap':osm, 'Kartverket topo':topo}).addTo(map);
const routeLayer = L.layerGroup().addTo(map), candidateLayer = L.layerGroup().addTo(map);
const markers = {};
function status(message, error=false) {$('status').textContent=message; $('status').className=error?'error':'';}
async function api(url, options={}) {const response=await fetch(url,options); if(!response.ok){let body=await response.json().catch(()=>({detail:response.statusText})); throw Error(typeof body.detail==='string'?body.detail:JSON.stringify(body.detail));}return response.json();}
function coords(name){const values=$(name).value.split(',').map(Number);if(values.length!==2||!values.every(Number.isFinite)||Math.abs(values[0])>90||Math.abs(values[1])>180)throw Error('Enter latitude, longitude for endpoint '+name.toUpperCase());return values;}
function mark(name,latlng){$(name).value=latlng.map(n=>Number(n).toFixed(6)).join(', ');if(markers[name])markers[name].setLatLng(latlng);else{markers[name]=L.marker(latlng,{draggable:true,icon:L.divIcon({className:'site-marker '+(name==='b'?'destination':''),html:name.toUpperCase(),iconSize:[32,32]})}).addTo(map);markers[name].on('dragend',e=>{const p=e.target.getLatLng();mark(name,[p.lat,p.lng]);invalidate();});}}
function invalidate(){result=null;routeLayer.clearLayers();candidateLayer.clearLayers();$('metrics').replaceChildren();$('hops').hidden=true;$('profile').hidden=true;$('exports').hidden=true;$('result-title').textContent='Ready for a new route';}
for(const name of ['a','b']){$(name).onchange=()=>{try{mark(name,coords(name));invalidate();}catch(e){status(e.message,true);}};mark(name,coords(name));}
document.querySelectorAll('[data-place]').forEach(b=>b.onclick=()=>{placing=b.dataset.place;$('map-hint').textContent='Click the map to place endpoint '+placing.toUpperCase();});
map.on('click',e=>{if(placing&&!busy){mark(placing,[e.latlng.lat,e.latlng.lng]);placing=null;invalidate();$('map-hint').textContent='Drag a marker to fine-tune its position';}});
$('fit').onclick=()=>map.fitBounds([coords('a'),coords('b')],{padding:[60,60],maxZoom:14});
const definitions=[['frequency_mhz','Frequency · MHz'],['tx_power_dbm','TX power · dBm'],['receiver_sensitivity_dbm','Sensitivity · dBm'],['fade_margin_db','Fade margin · dB']];
function input(parent,obj,key,label){const l=document.createElement('label');l.textContent=label;const i=document.createElement('input');i.type='number';i.step='any';i.value=obj[key]??'';i.dataset.key=key;i.onchange=()=>{obj[key]=i.value===''?null:Number(i.value);invalidate();};l.append(i);parent.append(l);}
function group(parent,obj,defs){const box=document.createElement('div');box.className='fields';defs.forEach(([key,label])=>input(box,obj,key,label));parent.append(box);}
function select(parent,obj,key,label,options){const l=document.createElement('label');l.textContent=label;const s=document.createElement('select');for(const [value,text] of options){const o=document.createElement('option');o.value=value;o.textContent=text;s.append(o);}s.value=obj[key];s.onchange=()=>{obj[key]=s.value;invalidate();};l.append(s);parent.append(l);}
function details(title){const d=document.createElement('details'),s=document.createElement('summary');s.textContent=title;d.append(s);$('settings').append(d);return d;}
function buildSettings(){const box=$('settings');box.replaceChildren();group(box,rf,definitions);select(box,rf,'validation_mode','Validation',[['rf_propagation','RF propagation / diffraction'],['strict_los','Strict LOS + Fresnel']]);let d=details('Antennas & propagation');for(const [key,label] of [['endpoint_a','Endpoint A'],['endpoint_b','Endpoint B'],['router','Repeaters']]){const title=document.createElement('p');title.textContent=label;d.append(title);group(d,rf[key],[['height_agl_m','Height AGL · m'],['gain_dbi','Gain · dBi'],['feed_loss_db','Feed loss · dB']]);}group(d,rf,[['k_factor','Earth k-factor'],['required_fresnel_clearance','Fresnel ratio · 0–1'],['miscellaneous_loss_db','Misc. loss · dB']]);d=details('Search & optimization');select(d,candidates,'priority','Objective',[['minimum_routers','Minimum repeaters'],['minimum_infrastructure','Minimum infrastructure'],['maximum_reliability','Maximum reliability']]);group(d,candidates,[['corridor_width_m','Corridor · m'],['grid_spacing_m','Grid spacing · m'],['maximum_candidates','Max candidates'],['maximum_neighbors_per_site','Neighbors per site'],['maximum_link_distance_m','Max hop · m (blank = auto)'],['refine_radius_m','Refinement radius · m'],['refine_step_m','Refinement step · m'],['final_sample_step_m','Final sample step · m']]);}
async function refresh(){const data=await api('/api/state');for(const kind of ['dtm','dom'])$(kind+'-count').textContent=data.terrain[kind].length+' '+kind.toUpperCase()+' tiles';$('surface-note').textContent=data.terrain.dom.length?'Surface terrain loaded — includes obstruction geometry.':'Surface obstruction data unavailable — terrain only.';return data;}
function setBusy(value){busy=value;$('optimize').disabled=value;$('cancel').hidden=!value;document.querySelectorAll('aside input, aside select, [data-place], [data-clear], #open').forEach(el=>el.disabled=value);Object.values(markers).forEach(marker=>value?marker.dragging.disable():marker.dragging.enable());$('progress').hidden=!value;}
for(const kind of ['dtm','dom'])$(kind).onchange=async e=>{setBusy(true);try{for(const file of e.target.files){status('Uploading '+file.name+'…');const data=new FormData();data.append('file',file);const uploaded=await api('/api/terrain/'+kind,{method:'POST',body:data});map.fitBounds(uploaded.bounds);}invalidate();await refresh();status('Terrain uploaded. Place endpoints inside the covered area.');}catch(e){status(e.message,true);}finally{setBusy(false);$(kind).value='';}};
document.querySelectorAll('[data-clear]').forEach(b=>b.onclick=async()=>{try{await api('/api/terrain/'+b.dataset.clear,{method:'DELETE'});invalidate();await refresh();}catch(e){status(e.message,true);}});
function plan(){return {format:'repeaternet-web',version:1,a:coords('a'),b:coords('b'),rf,candidates};}
$('save').onclick=()=>{try{const blob=new Blob([JSON.stringify(plan(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='route.webplan.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){status(e.message,true);}};
function load(data){if(!Array.isArray(data.a)||!Array.isArray(data.b)||!data.rf||!data.candidates)throw Error('Choose a RepeaterNet .webplan.json file');rf=data.rf;candidates=data.candidates;mark('a',data.a);mark('b',data.b);coords('a');coords('b');buildSettings();invalidate();$('fit').click();}
$('open').onchange=async e=>{try{load(JSON.parse(await e.target.files[0].text()));status('Plan opened. Upload matching terrain if needed.');}catch(e){status(e.message,true);}e.target.value='';};
$('optimize').onclick=async()=>{try{const body=plan();invalidate();await api('/api/optimize',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});setBusy(true);poll();}catch(e){status(e.message,true);}};
$('cancel').onclick=async()=>{try{await api('/api/cancel',{method:'POST'});status('Cancelling…');}catch(e){status(e.message,true);}};
async function poll(){try{const {job}=await refresh();status(job.stage,job.state==='error');if(job.state==='running'){$('progress').max=Math.max(job.total||1,1);$('progress').value=job.done||0;setTimeout(poll,800);return;}setBusy(false);if(job.state==='complete'){result=await api('/api/result');render();}}catch(e){setBusy(false);status(e.message,true);}}
function render(){routeLayer.clearLayers();$('metrics').replaceChildren();$('hops').querySelector('tbody').replaceChildren();$('result-title').textContent=result.found?'Your connection, mapped.':'No viable route found';if(!result.found){status(result.diagnostics.join(' · ')||'Try a wider corridor or different antenna heights.');return;}const links=result.links;for(const [value,label] of [[result.router_count,'REPEATERS'],[(links.reduce((s,l)=>s+l.distance_m,0)/1000).toFixed(1)+' km','TOTAL DISTANCE'],[Math.min(...links.map(l=>l.worst_margin_db)).toFixed(1)+' dB','BOTTLENECK MARGIN'],[result.elapsed_seconds.toFixed(1)+' s','SEARCH TIME']]){const d=document.createElement('div');d.className='metric';const strong=document.createElement('strong'),small=document.createElement('small');strong.textContent=value;small.textContent=label;d.append(strong,small);$('metrics').append(d);}const sites=Object.fromEntries(result.route.map(s=>[s.id,s]));result.route.filter(s=>s.kind==='router').forEach(s=>L.marker([s.latitude,s.longitude],{icon:L.divIcon({className:'site-marker',html:s.id.replace(/[^A-Za-z0-9]/g,''),iconSize:[32,32]})}).bindTooltip(s.id).addTo(routeLayer));links.forEach((l,index)=>{const a=sites[l.source_id],b=sites[l.target_id];if(a&&b)L.polyline([[a.latitude,a.longitude],[b.latitude,b.longitude]],{color:l.valid?'#176750':'#b44735',weight:4}).addTo(routeLayer).on('click',()=>profile(index));const tr=document.createElement('tr');for(const v of [l.source_id+' → '+l.target_id,(l.distance_m/1000).toFixed(2)+' km',l.worst_margin_db.toFixed(1)+' dB',l.minimum_fresnel_clearance_ratio===null?'—':(l.minimum_fresnel_clearance_ratio*100).toFixed(0)+'%',l.los_clear?'Clear':'Obstructed',l.valid?'Valid':'Invalid']){const td=document.createElement('td');td.textContent=v;tr.append(td);}tr.tabIndex=0;tr.onclick=()=>profile(index);tr.onkeydown=e=>{if(e.key==='Enter')profile(index);};$('hops').querySelector('tbody').append(tr);});$('hops').hidden=false;$('exports').hidden=false;status('Calculation complete. Select a link to inspect its terrain profile.');showCandidates();if(links.length)profile(0);}
function showCandidates(){candidateLayer.clearLayers();if($('show-candidates').checked&&result)result.candidates.forEach(s=>L.circleMarker([s.latitude,s.longitude],{radius:3,color:'#778e7d',weight:1}).addTo(candidateLayer));}
$('show-candidates').onchange=showCandidates;
function profile(index){selected=index;const l=result.links[index],p=l.profile;if(!p)return;$('profile').hidden=false;$('profile-title').textContent=l.source_id+' → '+l.target_id+' · terrain & Fresnel clearance';document.querySelectorAll('#hops tbody tr').forEach((tr,i)=>tr.classList.toggle('selected',i===index));const canvas=$('chart'),width=canvas.clientWidth,height=230,ratio=devicePixelRatio||1;canvas.width=width*ratio;canvas.height=height*ratio;const ctx=canvas.getContext('2d');ctx.scale(ratio,ratio);const ground=p.dtm_elevation_m.map((v,i)=>v+p.earth_bulge_m[i]),surface=p.surface_elevation_m.map((v,i)=>v+p.earth_bulge_m[i]),fresnel=p.los_elevation_m.map((v,i)=>v-rf.required_fresnel_clearance*p.fresnel_radius_m[i]);const all=[...ground,...surface,...p.los_elevation_m,...fresnel].filter(Number.isFinite),min=Math.min(...all)-10,max=Math.max(...all)+10;const x=i=>45+(width-60)*i/(ground.length-1),y=v=>height-28-(v-min)/(max-min)*(height-45);ctx.font='10px Segoe UI';for(let i=0;i<5;i++){const v=min+(max-min)*i/4;ctx.fillStyle='#88968c';ctx.fillText(v.toFixed(0)+'m',0,y(v));ctx.strokeStyle='#dfe6df';ctx.beginPath();ctx.moveTo(43,y(v));ctx.lineTo(width,y(v));ctx.stroke();}for(const [data,color] of [[ground,'#94785d'],...(p.surface_available?[[surface,'#508c62']]:[]),[p.los_elevation_m,'#457bab'],[fresnel,'#d69a45']]){ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();data.forEach((v,i)=>i?ctx.lineTo(x(i),y(v)):ctx.moveTo(x(i),y(v)));ctx.stroke();}ctx.fillStyle='#88968c';ctx.fillText('0 km',45,height-5);ctx.fillText((l.distance_m/1000).toFixed(2)+' km',width-60,height-5);$('budget').textContent='Forward / reverse usable margin: '+l.forward.usable_margin_db.toFixed(2)+' / '+l.reverse.usable_margin_db.toFixed(2)+' dB\nFSPL: '+l.forward.fspl_db.toFixed(2)+' dB · Diffraction: '+l.diffraction_loss_db.toFixed(2)+' dB · Received: '+l.forward.received_power_dbm.toFixed(2)+' dBm\n'+(p.surface_available?'Surface obstruction data included.':'Surface obstruction data unavailable — terrain only.');}
window.addEventListener('resize',()=>{if(result?.links.length)profile(selected);});
(async()=>{try{const data=await refresh();rf=data.rf;candidates=data.candidates;if(data.plan)load(data.plan);else buildSettings();if(data.job.state==='running'){setBusy(true);poll();}}catch(e){status(e.message,true);}})();
